import type {
  AnalysisDraft,
  AutomationCandidate,
  EvidenceArtifact,
  ReviewItem,
  TraceLink,
  WorkflowEdge,
  WorkflowStep,
} from '../types/studio.js'

const defaultArtifacts = (): EvidenceArtifact[] => [
  {
    id: 'artifact-jira-story',
    artifactType: 'tracker-export',
    source: 'tracker',
    title: 'Jira Story Export',
    summary: 'Story scope, acceptance criteria, story points, and owner metadata.',
    rawText:
      'JIRA-184 | Story points: 3 | Acceptance criteria agreed | Owner: Product + Engineer',
    extractionStatus: 'ready',
    warnings: [],
    payload: {
      issueKey: 'JIRA-184',
      storyPoints: 3,
      acceptanceCriteria: 4,
      owner: 'Engineering',
    },
  },
  {
    id: 'artifact-repo-docs',
    artifactType: 'repo-doc',
    source: 'filesystem',
    title: 'Repository Docs Bundle',
    summary: 'Contribution guide, README, and test commands show TDD and validation flow.',
    rawText: 'README + CONTRIBUTING mention TDD, lint, typecheck, and test gates before PR.',
    extractionStatus: 'ready',
    warnings: [],
    payload: {
      files: ['README.md', 'CONTRIBUTING.md'],
      commands: ['npm test', 'npm run lint', 'npm run typecheck'],
    },
  },
  {
    id: 'artifact-review-sop',
    artifactType: 'review-artifact',
    source: 'review',
    title: 'PR Review Notes',
    summary: 'Critical and medium findings must be fixed before merge.',
    rawText: 'PR review policy: remediate critical and medium issues before merge approval.',
    extractionStatus: 'ready',
    warnings: [],
    payload: {
      blockingSeverities: ['critical', 'medium'],
      reviewer: 'Codex PR review',
    },
  },
]

const defaultSteps = (): WorkflowStep[] => [
  {
    id: 'jira-scope',
    name: 'Capture Jira story scope',
    owner: 'Product Manager',
    input: 'Jira story, story points, acceptance criteria',
    output: 'Scoped requirement and delivery target',
    storyPoints: 3,
    tools: ['Jira'],
    automationMode: 'manual',
    errorSensitivity: 'medium',
    reviewRequired: true,
    validationRequired: false,
    effortHours: 1.2,
    throughputContribution: 0.85,
    notes: 'Story point sizing is used as the baseline speed and cost index.',
    confirmationState: 'reviewed',
  },
  {
    id: 'acceptance-alignment',
    name: 'Clarify acceptance and implementation approach',
    owner: 'Engineering Lead',
    input: 'Scoped story and constraints',
    output: 'Implementation plan and TDD acceptance checklist',
    storyPoints: 3,
    tools: ['Jira', 'Repo docs'],
    automationMode: 'assist-only',
    errorSensitivity: 'medium',
    reviewRequired: true,
    validationRequired: false,
    effortHours: 1.4,
    throughputContribution: 0.9,
    notes: 'Use evidence to confirm assumptions before coding begins.',
    confirmationState: 'drafted',
  },
  {
    id: 'tdd-implementation',
    name: 'Execute TDD coding loop',
    owner: 'Engineer',
    input: 'Accepted scope and failing tests',
    output: 'Working implementation with passing targeted tests',
    storyPoints: 3,
    tools: ['Codex', 'Editor', 'Test runner'],
    automationMode: 'assist-only',
    errorSensitivity: 'high',
    reviewRequired: true,
    validationRequired: true,
    effortHours: 4.2,
    throughputContribution: 1,
    notes: 'Write a failing test first, then implement the smallest passing change.',
    confirmationState: 'drafted',
  },
  {
    id: 'validation-gate',
    name: 'Run validation gate',
    owner: 'Engineer',
    input: 'Changed code and regression tests',
    output: 'Passing test, lint, typecheck, and build evidence',
    storyPoints: 3,
    tools: ['Vitest', 'ESLint', 'TypeScript', 'Vite'],
    automationMode: 'automate-with-review',
    errorSensitivity: 'high',
    reviewRequired: true,
    validationRequired: true,
    effortHours: 1.1,
    throughputContribution: 0.88,
    notes: 'This gate is the main speed and cost checkpoint for each story point slice.',
    confirmationState: 'reviewed',
  },
  {
    id: 'pr-open',
    name: 'Open pull request',
    owner: 'Engineer',
    input: 'Validated branch',
    output: 'PR with implementation summary and evidence',
    storyPoints: 3,
    tools: ['GitHub'],
    automationMode: 'assist-only',
    errorSensitivity: 'medium',
    reviewRequired: true,
    validationRequired: false,
    effortHours: 0.6,
    throughputContribution: 0.62,
    notes: 'PR should clearly attach validation evidence and intended reviewer loop.',
    confirmationState: 'drafted',
  },
  {
    id: 'review-remediation',
    name: 'Review and remediate blocking findings',
    owner: 'Engineer',
    input: 'Codex and human review findings',
    output: 'Critical and medium issues cleared for merge',
    storyPoints: 3,
    tools: ['GitHub', 'Codex PR review'],
    automationMode: 'automate-with-review',
    errorSensitivity: 'high',
    reviewRequired: true,
    validationRequired: true,
    effortHours: 1.7,
    throughputContribution: 0.78,
    notes: 'Critical and medium findings must be resolved before merge readiness.',
    confirmationState: 'drafted',
  },
]

const defaultEdges = (): WorkflowEdge[] => [
  {
    id: 'edge-scope-alignment',
    sourceStepId: 'jira-scope',
    targetStepId: 'acceptance-alignment',
    type: 'handoff',
    label: 'approved scope',
  },
  {
    id: 'edge-alignment-tdd',
    sourceStepId: 'acceptance-alignment',
    targetStepId: 'tdd-implementation',
    type: 'handoff',
    label: 'ready to build',
  },
  {
    id: 'edge-tdd-validation',
    sourceStepId: 'tdd-implementation',
    targetStepId: 'validation-gate',
    type: 'handoff',
    label: 'candidate change set',
  },
  {
    id: 'edge-validation-pr',
    sourceStepId: 'validation-gate',
    targetStepId: 'pr-open',
    type: 'handoff',
    label: 'green checks',
  },
  {
    id: 'edge-pr-review',
    sourceStepId: 'pr-open',
    targetStepId: 'review-remediation',
    type: 'handoff',
    label: 'review findings',
  },
  {
    id: 'edge-review-rework',
    sourceStepId: 'review-remediation',
    targetStepId: 'tdd-implementation',
    type: 'rework-loop',
    label: 'rework loop',
  },
]

const defaultReviewQueue = (): ReviewItem[] => [
  {
    id: 'review-story-points',
    label: 'Confirm story point signal for speed and cost analysis',
    field: 'storyPoints',
    stepId: 'jira-scope',
    confidence: 'low',
    reason: 'Tracker export includes sizing, but teams use story points differently.',
  },
  {
    id: 'review-validation-gate',
    label: 'Verify full validation gate matches your actual checks',
    field: 'validationRequired',
    stepId: 'validation-gate',
    confidence: 'medium',
    reason: 'Repo evidence suggests test/lint/typecheck/build, but build may not block every team.',
  },
  {
    id: 'review-pr-policy',
    label: 'Confirm PR remediation policy for critical and medium findings',
    field: 'reviewPolicy',
    stepId: 'review-remediation',
    confidence: 'medium',
    reason: 'Review artifact indicates blocking severities, but org policy may differ.',
  },
]

const defaultAutomationCandidates = (): AutomationCandidate[] => [
  {
    stepId: 'acceptance-alignment',
    label: 'Draft implementation approach from story evidence',
    opportunity: 'assist-only',
    rationale: 'Useful drafting step, but still needs engineering review.',
  },
  {
    stepId: 'validation-gate',
    label: 'Run deterministic validation suite automatically',
    opportunity: 'review-gated',
    rationale: 'High leverage and already tool-driven, but results need human interpretation.',
  },
  {
    stepId: 'review-remediation',
    label: 'Generate remediation plan from Codex PR review findings',
    opportunity: 'review-gated',
    rationale: 'Can accelerate fixes while keeping blocking severity checks human-governed.',
  },
]

const defaultTraceLinks = (): Record<string, TraceLink[]> => ({
  'jira-scope': [
    {
      artifactId: 'artifact-jira-story',
      artifactTitle: 'Jira Story Export',
      excerpt: 'Story points: 3 | Acceptance criteria agreed',
      inferredField: 'scope and story points',
      confidence: 'high',
    },
  ],
  'validation-gate': [
    {
      artifactId: 'artifact-repo-docs',
      artifactTitle: 'Repository Docs Bundle',
      excerpt: 'README + CONTRIBUTING mention TDD, lint, typecheck, and test gates before PR.',
      inferredField: 'validation gate',
      confidence: 'high',
    },
  ],
  'review-remediation': [
    {
      artifactId: 'artifact-review-sop',
      artifactTitle: 'PR Review Notes',
      excerpt: 'remediate critical and medium issues before merge approval',
      inferredField: 'review remediation policy',
      confidence: 'medium',
    },
  ],
})

export function buildDefaultAgileWorkflow(): AnalysisDraft {
  return {
    workflowName: 'Agile Story Delivery',
    storyPoints: 3,
    steps: defaultSteps(),
    edges: defaultEdges(),
    artifacts: defaultArtifacts(),
    reviewQueue: defaultReviewQueue(),
    bottlenecks: [
      'Validation gate bundles multiple checks and can dominate cycle time for small stories.',
      'PR remediation loop is variable and often drives the final merge delay.',
    ],
    automationCandidates: defaultAutomationCandidates(),
    traceLinks: defaultTraceLinks(),
    baseline: {
      humanEffortHours: 10.2,
      cycleTimeHours: 18,
      outputVolume: 1,
      qualityScore: 87,
      reviewBurdenHours: 2.7,
      storyPoints: 3,
      costPerHourUsd: 115,
    },
  }
}
